@startuml

class Ingresso {
    - id int
    - numeroAssento int
    - preco float
    - nomeFilme string
    + criarIngresso(id, numeroAssento, preco, nomeFilme)
    + editarIngresso(id)
    + deletarIngresso(idgit)
    
}

@enduml