@startuml cinema 

class Pessoa{
    - id int
    - nome String
    - idade int
    - Email String
    - CPF int
    - gênero String
    + criarPessoa(nome, idade, Email, CPF, gênero)
    + editarPessoa(id)
    + deletarPessoa(id)

}

