@startuml Cinema

class cinema{
    - id int
    - nome String
    - endereço String
    + criarSala(nome, endereço)
    + editarSala(id)
    + deletarSala(idgit)
}

class Ingresso {
    - id int
    - numeroAssento int
    - preco float
    - nomeFilme string
    + criarIngresso(id, numeroAssento, preco, nomeFilme)
    + editarIngresso(id)
    + deletarIngresso(idgit)
    
}

class Pessoa{
    - id int
    - nome String
    - idade int
    - Email String
    - CPF int
    - gênero String
    + criarPessoa(nome, idade, Email, CPF, gênero)
    + editarPessoa(id)
    + deletarPessoa(id)

}

class Sala{
    - id int
    - numeroSala int 
    - qtdAssentos int 
    + criarSala (numeroSala, qtdAssentos)
    + editarSala (id)
    + deletarSala (id)
}

class Sessao{
    -id int
    -filme string
    -sala Sala
    +consultarSessao(id)
    +cadastrarSessao(filme, sala)
    +deletarSessao(id)
}
@enduml
